### ISSUE TITLE
Feature Request : Sort  / limit by context

### ISSUE THREAD

**Issue by neoneddy** [mjb123uk/FormDataManager#1]
Would be nice to have a way to sort or limit by context.  Formit has this which is nice, I have a few clients that use multicontext installs.

Let me know how I can help, I'm not opposed to a bounty.

**Comment by mjb123uk** [comment]
I will add this in the next release, due soon.

**Comment by neoneddy** [comment]
Thanks!!

**Comment by mjb123uk** [comment]
New version 1.4.0 released today.
I have added the formit context key column to the formit grid/list. By default this is hidden, use the new system setting to turn on this feature.  I have made the grid sortable by name or context so hopefully this will help your clients identify the form data they wish to view/export.
